<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
</head>
<body>
<div style="width: 1272px; height: 1349px">
  <div style="width: 1272px; height: 1349px; left: 0px; top: 0px; position: absolute; background: #9C9A95">
    <img style="width: 225px; height: 98px; left: 197px; top: 1911px; position: absolute; box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25)" src="https://via.placeholder.com/225x98" />
    <div style="width: 1280px; height: 1349px; left: 0px; top: 0px; position: absolute">
      <div style="width: 1280px; height: 94px; left: 0px; top: 0px; position: absolute">
        <div style="width: 1280px; height: 94px; left: 0px; top: 0px; position: absolute; background: #61605E">
          <div style="left: 178px; top: 36px; position: absolute; color: white; font-size: 18px; font-family: Inria Serif; font-weight: 400; word-wrap: break-word">HOME</div>
          <div style="left: 373px; top: 36px; position: absolute; color: white; font-size: 18px; font-family: Inria Serif; font-weight: 400; word-wrap: break-word">DISCOUNT</div>
          <div style="left: 278px; top: 36px; position: absolute; color: white; font-size: 18px; font-family: Inria Serif; font-weight: 400; word-wrap: break-word">SHOP</div>
          <div style="left: 497px; top: 36px; position: absolute; color: white; font-size: 18px; font-family: Inria Serif; font-weight: 400; word-wrap: break-word">REVIEWS</div>
          <div style="width: 208px; height: 29px; left: 905px; top: 33px; position: absolute; background: #888988; border-radius: 10px; border: 0.50px black solid"></div>
          <img style="width: 165px; height: 72px; left: -14px; top: -3px; position: absolute; box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25)" src="https://via.placeholder.com/165x72" />
          <div style="left: 915px; top: 38px; position: absolute; opacity: 0.40; color: black; font-size: 16px; font-family: Inria Serif; font-weight: 400; word-wrap: break-word">Search.....</div>
          <div style="height: 15px; left: 1092px; top: 40px; position: absolute">
            <img style="width: 10.20px; height: 10.20px; left: 0px; top: 0px; position: absolute" src="https://via.placeholder.com/10x10" />
            <div style="width: 6.49px; height: 0px; left: 7.20px; top: 9.60px; position: absolute; transform: rotate(56.31deg); transform-origin: 0 0; background: #171616; border: 1px black solid"></div>
          </div>
          <div style="width: 276px; height: 275px; left: 964px; top: 78px; position: absolute"></div>
          <img style="width: 49px; height: 49px; left: 1206px; top: 21px; position: absolute; border-radius: 9999px" src="https://via.placeholder.com/49x49" />
        </div>
        <div style="width: 1280px; height: 434px; left: 0px; top: 72px; position: absolute; background: #61605E; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
          <img style="width: 521px; height: 597px" src="https://via.placeholder.com/521x597" />
          <div style="color: white; font-size: 40px; font-family: Junge; font-weight: 400; word-wrap: break-word">LOREM IPSUM</div>
          <div style="color: #BFB7B7; font-size: 20px; font-family: Junge; font-weight: 400; word-wrap: break-word">The place where you will find the best discounts.</div>
          <div style="text-align: center; color: #BFB7B7; font-size: 20px; font-family: Junge; font-weight: 400; word-wrap: break-word">Here you'll find everything you need to buy a new car,<br/> with great deals on sedans, crossovers and more. We<br/> work with leading automakers to bring you the best <br/>options at affordable prices.</div>
          <div style="width: 192px; height: 43px; background: #888988; border-radius: 30px; border: 0.50px black solid"></div>
          <div style="text-align: center; color: white; font-size: 20px; font-family: Junge; font-weight: 400; word-wrap: break-word">DISCOUNTS</div>
        </div>
      </div>
      <div style="width: 89px; height: 22px; left: 133px; top: 756px; position: absolute"></div>
      <div style="width: 250px; height: 218px; left: 359px; top: 591px; position: absolute">
        <div style="width: 250px; height: 218px; left: 0px; top: 0px; position: absolute; background: rgba(217, 217, 217, 0.30); border-radius: 10px; border: 0.50px black solid"></div>
        <img style="width: 203px; height: 114px; left: 22px; top: 85px; position: absolute" src="https://via.placeholder.com/203x114" />
      </div>
      <div style="width: 250px; height: 218px; left: 55px; top: 591px; position: absolute">
        <div style="width: 250px; height: 218px; left: 0px; top: 0px; position: absolute; background: rgba(217, 217, 217, 0.30); border-radius: 10px; border: 0.50px black solid"></div>
        <img style="width: 144px; height: 136px; left: 53px; top: 63px; position: absolute" src="https://via.placeholder.com/144x136" />
      </div>
      <div style="width: 250px; height: 218px; left: 663px; top: 591px; position: absolute">
        <div style="width: 250px; height: 218px; left: 0px; top: 0px; position: absolute; background: rgba(217, 217, 217, 0.30); border-radius: 10px; border: 0.50px black solid"></div>
        <img style="width: 113px; height: 149px; left: 68px; top: 56px; position: absolute; opacity: 0.80" src="https://via.placeholder.com/113x149" />
      </div>
      <div style="width: 250px; height: 218px; left: 967px; top: 591px; position: absolute">
        <div style="width: 250px; height: 218px; left: 0px; top: 0px; position: absolute; background: rgba(217, 217, 217, 0.30); border-radius: 10px; border: 0.50px black solid"></div>
        <img style="width: 163px; height: 124px; left: 46px; top: 75px; position: absolute" src="https://via.placeholder.com/163x124" />
      </div>
      <div style="width: 1280px; height: 94px; left: 0px; top: 0px; position: absolute">
        <div style="width: 1280px; height: 94px; left: 0px; top: 0px; position: absolute; background: #61605E">
          <img style="width: 165px; height: 72px; left: -14px; top: -3px; position: absolute; box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25)" src="https://via.placeholder.com/165x72" />
          <div style="width: 276px; height: 275px; left: 964px; top: 78px; position: absolute"></div>
          <img style="width: 49px; height: 49px; left: 1206px; top: 21px; position: absolute; border-radius: 9999px" src="https://via.placeholder.com/49x49" />
          <div style="left: 151px; top: 38px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Главная</div>
          <div style="left: 387px; top: 38px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Скидочные акции</div>
          <div style="left: 265px; top: 38px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Магазин</div>
          <div style="left: 595px; top: 38px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; text-transform: capitalize; word-wrap: break-word">Анализ</div>
          <div style="left: 707px; top: 40px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; text-transform: capitalize; word-wrap: break-word">Корзина</div>
        </div>
        <div style="width: 1280px; height: 434px; left: 0px; top: 72px; position: absolute; background: #61605E; flex-direction: column; justify-content: flex-start; align-items: flex-start; display: flex">
          <img style="width: 521px; height: 597px" src="https://via.placeholder.com/521x597" />
          <div style="color: white; font-size: 40px; font-family: Junge; font-weight: 400; word-wrap: break-word">LOREM IPSUM</div>
          <div style="width: 192px; height: 43px; background: #888988; border-radius: 30px; border: 0.50px black solid"></div>
        </div>
      </div>
      <div style="width: 281px; height: 41px; left: 503px; top: 1090px; position: absolute">
        <div style="width: 281px; height: 41px; left: 0px; top: 0px; position: absolute; background: #888988; border-radius: 30px; border: 0.50px black solid"></div>
        <div style="left: 49px; top: 7px; position: absolute; text-align: center; color: white; font-size: 20px; font-family: Prata; font-weight: 400; word-wrap: break-word">Отправить заявку</div>
      </div>
      <div style="width: 137px; height: 13px; left: 246px; top: 884px; position: absolute; color: black; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">СВЯЗАТЬСЯ С<br/>НАМИ</div>
      <div style="width: 355.01px; height: 0px; left: 246px; top: 994px; position: absolute; border: 1px white solid"></div>
      <div style="width: 796px; height: 0px; left: 246px; top: 1049px; position: absolute; border: 1px white solid"></div>
      <div style="width: 355.01px; height: 0px; left: 687px; top: 996.49px; position: absolute; border: 1px white solid"></div>
      <div style="left: 246px; top: 970px; position: absolute; color: rgba(255, 255, 255, 0.50); font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Ваше имя</div>
      <div style="left: 246px; top: 1025px; position: absolute; color: rgba(255, 255, 255, 0.50); font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Ваша почта</div>
      <div style="left: 687px; top: 967px; position: absolute; color: rgba(255, 255, 255, 0.50); font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Ваша фамилия</div>
      <div style="width: 1272px; height: 165px; left: 0px; top: 1184px; position: absolute; background: #61605E">
        <img style="width: 165px; height: 72px; left: 537px; top: -12px; position: absolute; box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25)" src="https://via.placeholder.com/165x72" />
        <div style="width: 517px; height: 0px; left: 393px; top: 107px; position: absolute; border: 1px #969696 solid"></div>
        <div style="left: 548px; top: 136px; position: absolute; opacity: 0.50; color: white; font-size: 13px; font-family: Inria Serif; font-weight: 400; word-wrap: break-word">2024, Design by VPProdaction</div>
        <div style="left: 393px; top: 71px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Главная</div>
        <div style="left: 629px; top: 71px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Скидочные акции</div>
        <div style="left: 507px; top: 71px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Магазин</div>
        <div style="left: 837px; top: 71px; position: absolute; color: white; font-size: 18px; font-family: Prata; font-weight: 400; text-transform: capitalize; word-wrap: break-word">Анализ</div>
      </div>
      <div style="width: 466px; height: 88px; left: 173px; top: 265px; position: absolute; color: #BFB7B7; font-size: 15px; font-family: Prata; font-weight: 400; word-wrap: break-word">Здесь вы найдете все необходимое для покупки нового автомобиля,
        с выгодными предложения-ми на седаны, кроссоверы и многое другое. Мы
        работаем с ведущими автопроизводителями, чтобы предложить вам лучшие варианты по доступным ценам.</div>
      <div style="width: 489px; height: 25px; left: 173px; top: 225px; position: absolute; color: #BFB7B7; font-size: 15px; font-family: Prata; font-weight: 400; word-wrap: break-word">Это место, где вы найдете лучшие скидки.</div>
      <div style="left: 235px; top: 394px; position: absolute; text-align: center; color: white; font-size: 18px; font-family: Prata; font-weight: 400; word-wrap: break-word">Скидки</div>
      <div style="left: 529px; top: 523px; position: absolute; color: #FFF9F9; font-size: 25px; font-family: Prata; font-weight: 400; word-wrap: break-word">Наши преимущества</div>
      <div style="left: 90px; top: 608px; position: absolute; color: black; font-size: 20px; font-family: Prata; font-weight: 400; line-height: 25px; word-wrap: break-word">Широкий выбор <br/>            акций</div>
      <div style="left: 368px; top: 608px; position: absolute; color: black; font-size: 20px; font-family: Prata; font-weight: 400; line-height: 25px; word-wrap: break-word">Персонализированные   <br/>         рекомендации</div>
      <div style="left: 677px; top: 608px; position: absolute; color: black; font-size: 20px; font-family: Prata; font-weight: 400; line-height: 25px; word-wrap: break-word">Легкость использова-<br/>            ния сайта</div>
      <div style="left: 986px; top: 608px; position: absolute"><span style="color: black; font-size: 20px; font-family: Prata; font-weight: 400; text-transform: capitalize; line-height: 25px; word-wrap: break-word">        н</span><span style="color: black; font-size: 20px; font-family: Prata; font-weight: 400; text-transform: lowercase; line-height: 25px; word-wrap: break-word">АДЕЖНОСТЬ И
      <br/>АКТУАЛЬНОСТЬ ДАННЫХ</span></div>
    </div>
  </div>
</div>
</body>
</html>
